# Generated by Django 5.0.4 on 2024-11-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
    ]
